require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - "bin/**"
    - "db/schema.rb"
    - "vendor/**/*"
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.0
  NewCops: enable

#s
# -----------------------------------------------------------------------------
#                                   RAILS

Rails:
  Enabled: True

Rails/ApplicationRecord:
  Exclude:
    - "db/migrate/**/*"

Rails/SkipsModelValidations:
  Exclude:
    - "db/migrate/**/*"

#
# -----------------------------------------------------------------------------
#                                   RSPEC

RSpec:
  Include:
    - "spec/**/*_spec.rb"
    - "spec/spec_helper.rb"
    - "spec/rails_helper.rb"

RSpec/ContextWording:
  Enabled: False

RSpec/ExampleLength:
  Enabled: False

RSpec/ExpectInHook:
  Enabled: False

RSpec/FilePath:
  Exclude:
    - "spec/client/**/*_spec.rb"

RSpec/MessageSpies:
  Enabled: False

RSpec/MissingExampleGroupArgument:
  Enabled: False

RSpec/MultipleExpectations:
  Enabled: False

RSpec/NestedGroups:
  Max: 5

RSpec/FactoryBot/CreateList:
  Enabled: False

#
# -----------------------------------------------------------------------------
#                                   Layout

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end
  SupportedStyles:
    - case
    - end
  IndentOneStep: True

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Exclude:
    - "db/**/*"
    - "spec/**/*"
    - "config/**/*"

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: False

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

#
# -----------------------------------------------------------------------------
#                                    Lint

#
# False positives:
#   * expect { something }.to change { something } often triggers this
#
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*_spec.rb"

#
# You might need some groups for grouping (maybe)?
#
Lint/MixedRegexpCaptureTypes:
  Enabled: False

#
# -----------------------------------------------------------------------------
#                                   Metrics

Metrics/AbcSize:
  Enabled: False

Metrics/BlockLength:
  Exclude:
    - "db/**/*"
    - "spec/**/*"
    - "config/**/*"
    - "**/*.rake"

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Enabled: False

Metrics/MethodLength:
  Max: 25
  Exclude:
    - "db/**/*"

#
# -----------------------------------------------------------------------------
#                                   Style

#
# Disable due to https://github.com/rubocop/rubocop/issues/5953
#
Style/AccessModifierDeclarations:
  Enabled: False

#
# Both styles or mixtures are reasonable
#
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Enabled: False

#
# Would be better but unlikely...
#
Style/Documentation:
  Enabled: False

Style/RaiseArgs:
  EnforcedStyle: compact

#
# Quick single line rescues in specs
#
Style/RescueModifier:
  Exclude:
    - "spec/**/*_spec.rb"

#
# Quick single line rescues in specs
#
Style/RescueStandardError:
  Exclude:
    - "spec/**/*_spec.rb"

#
# Often used pattern in chaining subjects in specs
#
Style/Semicolon:
  Exclude:
    - "spec/**/*_spec.rb"

Style/SignalException:
  EnforcedStyle: only_raise
