require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  Exclude:
    - "bin/**"
    - "db/schema.rb"
    - "vendor/**/*"
  TargetRubyVersion: 3.3
  TargetRailsVersion: 7.2
  NewCops: enable

#
# ---------------------------------------------------------------------------
#                                   Layout

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: True
  SupportedStyles:
    - case
    - end

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Exclude:
    - "db/**/*"
    - "spec/**/*"
    - "config/**/*"

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: False

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

#
# ---------------------------------------------------------------------------
#                                    Lint

#
# False positives:
#   * expect { something }.to change { something } often triggers this
#
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*_spec.rb"

#
# You might need some groups for grouping (maybe)?
#
Lint/MixedRegexpCaptureTypes:
  Enabled: False

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

#
# ---------------------------------------------------------------------------
#                                   Metrics

Metrics/AbcSize:
  Enabled: False

Metrics/BlockLength:
  Exclude:
    - "db/**/*"
    - "spec/**/*"
    - "config/**/*"
    - "**/*.rake"

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

#
# ---------------------------------------------------------------------------
#                                  Naming

Naming/FileName:
  Exclude:
    - "**/Gemfile"
    - "**/Rakefile"
    - "**/Appraisals"

#
# ---------------------------------------------------------------------------
#                                   RAILS

Rails:
  Enabled: True

Rails/ApplicationRecord:
  Exclude:
    - "db/migrate/**/*"

Rails/SkipsModelValidations:
  Exclude:
    - "db/migrate/**/*"

#
# ---------------------------------------------------------------------------
#                                   RSPEC

RSpec/ContextWording:
  Enabled: False

RSpec/ExampleLength:
  Enabled: False

RSpec/ExpectInHook:
  Enabled: False

RSpec/MessageSpies:
  Enabled: False

RSpec/MissingExampleGroupArgument:
  Enabled: False

RSpec/MultipleExpectations:
  Enabled: False

RSpec/NestedGroups:
  Max: 5

RSpec/ScatteredSetup:
  Enabled: false

#
# ---------------------------------------------------------------------------
#                                   Style

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RedundantBegin:
  Enabled: false

Style/RescueModifier:
  Exclude:
    - "spec/**/*_spec.rb"

Style/RescueStandardError:
  Exclude:
    - "spec/**/*_spec.rb"

Style/Semicolon:
  Exclude:
    - "spec/**/*_spec.rb"

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrivialAccessors:
  AllowPredicates: true
