#

development: &dev
  default:
    uri: amqp://guest:guest@localhost/
    pool: 25
    exchange: mnemosyne

  alternative:
    host: localhost
    port: 5672
    vhost: /
    username: guest
    password: guest
    pool: 25
    exchange: mnemosyne

test:
  <<: *dev

production:
  <<: *dev
